{{- if .Values.admin.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: admin
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-admin
  namespace: {{ .Release.Namespace | quote }} 
data:
  ## Force UTC timezone
  TZ: "Etc/UTC"
  NODE_ENV: "production"
  {{- if .Values.global.mongoOplogUrl }}
  MONGO_OPLOG_URL: {{ .Values.global.mongoOplogUrl | quote }}
  {{- else }}
  MONGO_OPLOG_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/local?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  {{- if .Values.global.mongoUrl }}
  MONGO_URL: {{ .Values.global.mongoUrl | quote }}
  {{- else }}
  MONGO_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/reaction?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  OAUTH2_ADMIN_URL: {{ printf "http://%s-hydra.%s.svc:4445" ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  OAUTH2_IDP_PUBLIC_CHANGE_PASSWORD_URL: {{ printf "%s/account/change-password?email=EMAIL&from=FROM" ( include "reactioncommerce.identity.url" . ) | quote }}
  OAUTH2_PUBLIC_URL: {{ include "reactioncommerce.hydra.frontend.url" . | quote }}
  PORT: "4080"
  PUBLIC_FILES_BASE_URL: {{ include "reactioncommerce.api.url" . | quote }}
  PUBLIC_GRAPHQL_API_URL_HTTP: {{ printf "%s/graphql" ( include "reactioncommerce.api.url" . ) | quote }}
  PUBLIC_GRAPHQL_API_URL_WS: {{ printf "%s/graphql" ( include "reactioncommerce.api.socketUrl" . ) | quote }}
  PUBLIC_I18N_BASE_URL: {{ include "reactioncommerce.api.url" . | quote }}
  PUBLIC_STOREFRONT_HOME_URL: {{ include "reactioncommerce.web.url" . | quote }}
  ROOT_URL: {{ include "reactioncommerce.admin.url" . | quote }}
  GRAPHQL_PLAYGROUND_ENABLED: {{ .Values.api.enableGraphQlPlayground | default "false" | quote }}
  GRAPHQL_INTROSPECTION_ENABLED: {{ .Values.api.enableGraphQlIntrospection | default "false" | quote }}
{{- end }}
