{{- if .Values.identity.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: identity
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-identity
  namespace: {{ .Release.Namespace | quote }} 
data:
  ## Force UTC timezone
  TZ: "Etc/UTC"
  NODE_ENV: "production"
  API_URL: {{ printf "%s/graphql" .Values.api.rootUrl | quote }}
  HYDRA_ADMIN_URL: {{ printf "http://%s-hydra.%s.svc:4445" ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  HYDRA_TOKEN_URL: {{ printf "http://%s-hydra.%s.svc:4444/oauth2/token" ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  {{- if .Values.global.mongoOplogUrl }}
  MONGO_OPLOG_URL: {{ .Values.global.mongoOplogUrl | quote }}
  {{- else }}
  MONGO_OPLOG_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/local?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  {{- if .Values.global.mongoUrl }}
  MONGO_URL: {{ .Values.global.mongoUrl | quote }}
  {{- else }}
  MONGO_URL: {{ printf "mongodb://root:%s@%s-mongodb-headless.%s.svc:27017/reaction?replicaSet=rs0&authSource=admin" .Values.mongodb.mongodbRootPassword ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  {{- end }}
  OAUTH2_CLIENT_DOMAINS: {{ include "reactioncommerce.web.url" . | quote }}
  PORT: "4100"
  ROOT_URL: {{ include "reactioncommerce.identity.url" . | quote }}
{{- end }}
